apiVersion: v1
kind: Secret
metadata:
  name: example-204-validating-certs
type: Opaque
data:
  cert.crt: |
    {{ .Files.Get "validating-certs/cert.pem" | b64enc }}
  cert.key: |
    {{ .Files.Get "validating-certs/cert-key.pem" | b64enc }}
  ca.crt: |
    {{ .Files.Get "validating-certs/ca.pem" | b64enc }}
