apiVersion: v1
kind: Secret
metadata:
  name: example-210-conversion-certs
type: kubernetes.io/tls
data:
  tls.crt: |
    {{ .Files.Get "conversion-certs/tls.pem" | b64enc }}
  tls.key: |
    {{ .Files.Get "conversion-certs/tls-key.pem" | b64enc }}
  ca.crt: |
    {{ .Files.Get "conversion-certs/ca.pem" | b64enc }}
