---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-210-acc
  labels:
    heritage: example-210
---
# Create and update ValidatingWebhookConfiguration
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: example-210
  labels:
    heritage: example-210
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["list", "update"]
- apiGroups: ["stable.example.com"]
  resources: ["crontabs"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: example-210
  labels:
    heritage: example-210
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: example-210
subjects:
  - kind: ServiceAccount
    name: example-210-acc
    namespace: {{ .Release.Namespace }}
