apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.shellOperator.conversionWebhookServiceName }}
  labels:
    heritage: example-210
spec:
#  type: LoadBalancer
#  externalTrafficPolicy: Local
  ports:
    - name: conversion-webhook
      port: 443
      targetPort: 9681
      protocol: TCP
  selector:
    app: shell-operator-example-210
